# connectors.yaml - Configuration file for connectors

# Telegram connector
telegram:
  enabled: true
  channels:
    - name: "Golang News"
      url: "https://t.me/golang_news"
    - name: "Rust Language"
      url: "https://t.me/rustlang"
    - name: "Python Insider"
      url: "https://t.me/python"
  credentials:
    api_id: "your_api_id"
    api_hash: "your_api_hash"

# RSS connector
rss:
  enabled: true
  feeds:
    - name: "Hacker News"
      url: "https://news.ycombinator.com/rss"
    - name: "The Verge"
      url: "https://www.theverge.com/rss/index.xml"
    - name: "DEV Community"
      url: "https://dev.to/feed"
  settings:
    timeout: 30s
    user_agent: "NewsAggregator/1.0"

# Reddit connector
reddit:
  enabled: true
  subreddits:
    - name: "openai"
      url: "https://www.reddit.com/r/openai"
  settings:
    timeout: 30s
    user_agent: "NewsAggregator/1.0 (by /u/your_username)"
    client_id: "E-pT2_4nqzd0C7IBPAmSkA"
    client_secret: "mz_7fMTAzjtewggF5GImQMELMVYfTQ"
    username: "Educational_Heat5353"
    password: "YVr3HwBiYPdHYAhx@KA"
    limit: 25 # Number of posts to fetch per subreddit
    sort: "hot" # Options: hot, new, top, rising